server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${SCREENFORCE_EUREKA_SERVER_URL}
spring:
  application:
    name: screenforce-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: tech-screening-service
        uri: lb://tech-screening-service
        predicates:
        - Path=/screening/**
        filters:
        - RewritePath=/screening/(?<path>.*), /$\{path}
      - id: screening-admin-service
        uri: lb://screening-admin-service
        predicates:
        - Path=/admin/**
        filters:
        - RewritePath=/admin/(?<path>.*), /$\{path}
      - id: screening-report-service
        uri: lb://screening-report-service
        predicates:
        - Path=/report/**
        filters:
        - RewritePath=/report/(?<path>.*), /$\{path}